language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: gilbarbara@gmail.com
  api_key:
    secure: h5m4h06wL4TTM8YMfYHdE3clgAPObFFMCtgkf8MzrWEYLJxly9BO743uXRvD6+XUHWX4Iq045RZuLgk2vJJOoxIYhcC0aQzvZo7DCbLp2FPNLGdQ33gTJ2yKwKpLea/uHZlcUIuegwYNg2AuhwV+K9qMMApPUSSF1EMDZRbb5+tZlJxwiJ1rBHmyy8XAlc6raVTYox4ZDq1BGzHdorrUaD3rm7GO0iM4nprszxjVdp//tm+nKTiEPK1Mp33jEoapCvofFiEjN0mFiKH0MNlWJDbgFyq2dEd6l3AdaezZpQliGpLJea02iIn6aHIjd34/kXrDBov5D0OLPQ9cjyUfcZJ8t1KchCjRhDOxMZx3tA3u7bfagBbH+Y74ucWfNwbyL+5TrEheliw8y6w8YPQMwPm1T6dVIZ9wynJ7E2MHqI+BeV3T3HsWe3TjbHrRf/2Pha3QfYNnYsv4QY8FvZXMpckJPxU2n9+e5HA+CKKspOVjSQVKg4JI2gBECrr7psU19501lyU5mZYt5R40zo4xU3kstJzaHgCvm1YDOYBZMoy29XufWpWy44LHQ9P+LAzLmFR6/ibKLEkRnyM29ZxiW7330K/De187exuNpR0LcrkOyx0n5QNMPrtTAWZsmPsag5R8gVDZwTER973+T1uh6/pNbKJNHVeLQeRPxd9JroQ=
  on:
    tags: true
    repo: gilbarbara/disable-scroll
