language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: gilbarbara@gmail.com
  api_key:
    secure: lhQxa/oWChCKKW2T8RVjf1TZgleZBU+WNEeSvDrzGKcFLnD+1ucHrbcG5YKIvDVFRhQogFV2tG7jQxWMp8t3KrVG63fBWbUDWHXtswrnTCwhz9R7hqna+SiAiV4gcahQWdUxkU+0GU6QtsbX/ekJygSUnh1diumMEiP4gfX1kcyMkKyNP/kC9L0qLR6hVk8lFHxQ/MFD3EIDtHuVFDOmI4lbXTiQ6l/GGyWnvAoCFlGB6e/VKuNDkEDXamfPGF2kzHkN0UlYI/tX+EygB+Nl8MNCViW1EToDhWl8n/4qnyUYYzFxEeTfWIcmeUGqmrf2seiDLaD8ahqNTMLQOybEFrU36Ds1gGEVdCwchGQCAYXebFr+4NqCHNlHh7Y4Cb/aFOB8VIsqzGonZi+gNXK3YO8lNn3Cl0EFSLeMuge5Al3pONexhIijDy9ZR8/U+ZexRsl7m8ZLvPsK7JOiAVen0qiZWdmOeax5ldT71NWljmtSTabOsf0+gHwZvscYw/QdE3vZqiwCRQdx2v+OtFa+eh8G3s2gKdE1vzMgFAF7MIXBBF/KbKrIUbgXgpv7gHs7xGDOzC5Ur806Knlw62rHIoVcCXskWR6wsVBVon+eEu6RrY3sm+TBQjPciC5lmGzIZoFi6P2SCw1N4cO2ree63JbA3I/g0Kt7TsspWd0SpaY=
  on:
    tags: true
    repo: gilbarbara/disable-scroll
